services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=courses'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=root'
    ports:
      - '3306'